#!/usr/bin/env groovy

def job_params = [
    [ $class: 'StringParameterValue',   name: "build_prefix",       value: "develop" ],
    [ $class: 'StringParameterValue',   name: "mayastorBranch",     value: "develop" ],
    [ $class: 'StringParameterValue',   name: "mcpBranch",          value: "develop" ],
    [ $class: 'BooleanParameterValue',  name: "build_images",       value: true ],
    [ $class: 'StringParameterValue',   name: "xray_test_plan",     value: "MQ-2743" ],
    [ $class: 'BooleanParameterValue',  name: "xray_send_report",   value: true ],
    [ $class: 'StringParameterValue',   name: "parallelism",        value: "10" ],
    [ $class: 'StringParameterValue',   name: "kubernetes_version", value: "1.21.8" ],
    [ $class: 'StringParameterValue',   name: "image_tag",          value: "" ],
    [ $class: 'StringParameterValue',   name: "test_profile",       value: "regression" ]
]

def Common() {
    def common = load "./pipelines/common2/common.groovy"
    return common
}

//The five time-and-date fields are as follows:
//minute (0-59), hour (0-23, 0 = midnight), day (1-31), month (1-12), weekday (0-6, 0 = Sunday).
// Daily => Monday to Friday. On Saturday and Sunday this pipeline will be
// invoked by the weekend pipeline.
String cron_schedule = "H 0 * * 1-5"

pipeline {
    agent any
    options {
      timeout(time: 12, unit: 'HOURS')
      buildDiscarder(logRotator(numToKeepStr: '365', artifactNumToKeepStr: '365'))
    }
    triggers {
      cron(cron_schedule)
    }
    stages {
        stage('RunTestJob') {
            steps {
                script {
                    Common().RunTestJob(job_params, "develop")
                }
            }
        }
    }
}
