testName: "replica_perturbation"
test: "MQ-1807"
e2eFioImage: ci-registry.mayastor-ci.mayadata.io/mayadata/e2e-fio
msnodes: 3
duration: 14d
sendEvent: 1
sendXrayTest: 1
replicaPerturbation:
  replicas: 3
  volumeSizeMb: 512
  fsvolume: 0
  localvolume: 0
  offlineDeviceTest: 1
  offlineDevAndReplicasTest: 1
  replicasTest: 1
  randomSleep: 0

