kind: Pod
apiVersion: v1
metadata:
  name: test-conductor
  namespace: mayastor-e2e
  labels:
    app: test-conductor
spec:
  containers:
    - name: test-conductor
      image: {{ .Values.registry }}mayadata/test_conductor:{{ .Values.tag }}
      imagePullPolicy: Always
      args:
        - "/test_conductor"
      env:
      - name: DURATION
        value: {{ .Values.duration }}
      - name: RUNNAME
        value: "{{ .Values.name }}"
      - name: SENDXRAYTEST
        value: "{{ .Values.sendxraytest }}"
      - name: SENDEVENT
        value: "{{ .Values.sendevent }}"
      ports:
        - containerPort: 8080
          protocol: "TCP"
          name: test-conductor
      volumeMounts:
      - name: tc-config
        mountPath: "/config.yaml"
        subPath: "config.yaml"
        readOnly: true
  tolerations:
  - key: openebs.io/role
    value: mayastor-e2e
    operator: "Equal"
    effect: "NoExecute"
  volumes:
  - name: tc-config
    configMap:
      name: tc-config
  restartPolicy: Never
  serviceAccountName: test-conductor-sa

