// Code generated by go-swagger; DO NOT EDIT.

package workload_monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mayastor-e2e/tools/extended-test-framework/test_conductor/wm/models"
)

// GetWorkloadsReader is a Reader for the GetWorkloads structure.
type GetWorkloadsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWorkloadsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWorkloadsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetWorkloadsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetWorkloadsOK creates a GetWorkloadsOK with default headers values
func NewGetWorkloadsOK() *GetWorkloadsOK {
	return &GetWorkloadsOK{}
}

/* GetWorkloadsOK describes a response with status code 200, with default header values.

Workload items were returned
*/
type GetWorkloadsOK struct {
	Payload []*models.Workload
}

func (o *GetWorkloadsOK) Error() string {
	return fmt.Sprintf("[GET /wm/workloads][%d] getWorkloadsOK  %+v", 200, o.Payload)
}
func (o *GetWorkloadsOK) GetPayload() []*models.Workload {
	return o.Payload
}

func (o *GetWorkloadsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWorkloadsNotFound creates a GetWorkloadsNotFound with default headers values
func NewGetWorkloadsNotFound() *GetWorkloadsNotFound {
	return &GetWorkloadsNotFound{}
}

/* GetWorkloadsNotFound describes a response with status code 404, with default header values.

no corresponding workload(s) were returned
*/
type GetWorkloadsNotFound struct {
}

func (o *GetWorkloadsNotFound) Error() string {
	return fmt.Sprintf("[GET /wm/workloads][%d] getWorkloadsNotFound ", 404)
}

func (o *GetWorkloadsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
