// Code generated by go-swagger; DO NOT EDIT.

package workload_monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteWorkloadsByRegistrantParams creates a new DeleteWorkloadsByRegistrantParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteWorkloadsByRegistrantParams() *DeleteWorkloadsByRegistrantParams {
	return &DeleteWorkloadsByRegistrantParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteWorkloadsByRegistrantParamsWithTimeout creates a new DeleteWorkloadsByRegistrantParams object
// with the ability to set a timeout on a request.
func NewDeleteWorkloadsByRegistrantParamsWithTimeout(timeout time.Duration) *DeleteWorkloadsByRegistrantParams {
	return &DeleteWorkloadsByRegistrantParams{
		timeout: timeout,
	}
}

// NewDeleteWorkloadsByRegistrantParamsWithContext creates a new DeleteWorkloadsByRegistrantParams object
// with the ability to set a context for a request.
func NewDeleteWorkloadsByRegistrantParamsWithContext(ctx context.Context) *DeleteWorkloadsByRegistrantParams {
	return &DeleteWorkloadsByRegistrantParams{
		Context: ctx,
	}
}

// NewDeleteWorkloadsByRegistrantParamsWithHTTPClient creates a new DeleteWorkloadsByRegistrantParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteWorkloadsByRegistrantParamsWithHTTPClient(client *http.Client) *DeleteWorkloadsByRegistrantParams {
	return &DeleteWorkloadsByRegistrantParams{
		HTTPClient: client,
	}
}

/* DeleteWorkloadsByRegistrantParams contains all the parameters to send to the API endpoint
   for the delete workloads by registrant operation.

   Typically these are written to a http.Request.
*/
type DeleteWorkloadsByRegistrantParams struct {

	/* Rid.

	   registrant uid

	   Format: uuid
	*/
	Rid strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete workloads by registrant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteWorkloadsByRegistrantParams) WithDefaults() *DeleteWorkloadsByRegistrantParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete workloads by registrant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteWorkloadsByRegistrantParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete workloads by registrant params
func (o *DeleteWorkloadsByRegistrantParams) WithTimeout(timeout time.Duration) *DeleteWorkloadsByRegistrantParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete workloads by registrant params
func (o *DeleteWorkloadsByRegistrantParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete workloads by registrant params
func (o *DeleteWorkloadsByRegistrantParams) WithContext(ctx context.Context) *DeleteWorkloadsByRegistrantParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete workloads by registrant params
func (o *DeleteWorkloadsByRegistrantParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete workloads by registrant params
func (o *DeleteWorkloadsByRegistrantParams) WithHTTPClient(client *http.Client) *DeleteWorkloadsByRegistrantParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete workloads by registrant params
func (o *DeleteWorkloadsByRegistrantParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRid adds the rid to the delete workloads by registrant params
func (o *DeleteWorkloadsByRegistrantParams) WithRid(rid strfmt.UUID) *DeleteWorkloadsByRegistrantParams {
	o.SetRid(rid)
	return o
}

// SetRid adds the rid to the delete workloads by registrant params
func (o *DeleteWorkloadsByRegistrantParams) SetRid(rid strfmt.UUID) {
	o.Rid = rid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteWorkloadsByRegistrantParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rid
	if err := r.SetPathParam("rid", o.Rid.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
