apiVersion: v1
kind: Service
metadata:
  name: test-director
<<<<<<< HEAD
  namespace: mayastor-e2e
=======
>>>>>>> 41dd1f8 (test(e2e): generate one set of files)
spec:
  type: NodePort
  selector:
    app: test-director
  ports:
    - port: 8080
<<<<<<< HEAD
=======
      #targetPort: 8080
>>>>>>> 41dd1f8 (test(e2e): generate one set of files)
---
kind: Pod
apiVersion: v1
metadata:
  name: test-director
<<<<<<< HEAD
  namespace: mayastor-e2e
=======
>>>>>>> 41dd1f8 (test(e2e): generate one set of files)
  labels:
    app: test-director
spec:
  containers:
    - name: test-director
      image: ci-registry.mayastor-ci.mayadata.io/mayadata/test_director:mhajek
      imagePullPolicy: Always
      args:
        - "/test_director"
      env:
      - name: PORT
        value: "8080"
      - name: HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      ports:
        - containerPort: 8080
          protocol: "TCP"
          name: test-dir
  restartPolicy: OnFailure

