apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-conductor-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: test-conductor-r
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: test-conductor-rb
subjects:
  - kind: ServiceAccount
    name: test-conductor-sa
    namespace: default
roleRef:
  kind: Role
  name: test-conductor-r
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-conductor-cr
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-conductor-crb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: test-conductor-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: test-conductor-cr
  apiGroup: rbac.authorization.k8s.io
---

kind: Pod
apiVersion: v1
metadata:
  name: test-conductor
  labels:
    app: test-conductor
spec:
  containers:
    - name: test-conductor
      image: ci-registry.mayastor-ci.mayadata.io/mayadata/test_conductor:cwd
      imagePullPolicy: Always
      args:
        - "/test_conductor"
      ports:
        - containerPort: 8080
          protocol: "TCP"
          name: test-conductor

  restartPolicy: OnFailure
  serviceAccountName: test-conductor-sa

