apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-monitor-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: workload-monitor-r
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: workload-monitor-rb
subjects:
  - kind: ServiceAccount
    name: workload-monitor-sa
    namespace: default
roleRef:
  kind: Role
  name: workload-monitor-r
  apiGroup: rbac.authorization.k8s.io
---

kind: Pod
apiVersion: v1
metadata:
  name: workload-monitor
  labels:
    app: workload-monitor
spec:
  containers:
    - name: workload-monitor
      image: ci-registry.mayastor-ci.mayadata.io/mayadata/workload_monitor:cwd
      args:
        - "/workload_monitor"
  restartPolicy: OnFailure
  serviceAccountName: workload-monitor-sa


