// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTestRunsParams creates a new GetTestRunsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTestRunsParams() *GetTestRunsParams {
	return &GetTestRunsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTestRunsParamsWithTimeout creates a new GetTestRunsParams object
// with the ability to set a timeout on a request.
func NewGetTestRunsParamsWithTimeout(timeout time.Duration) *GetTestRunsParams {
	return &GetTestRunsParams{
		timeout: timeout,
	}
}

// NewGetTestRunsParamsWithContext creates a new GetTestRunsParams object
// with the ability to set a context for a request.
func NewGetTestRunsParamsWithContext(ctx context.Context) *GetTestRunsParams {
	return &GetTestRunsParams{
		Context: ctx,
	}
}

// NewGetTestRunsParamsWithHTTPClient creates a new GetTestRunsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTestRunsParamsWithHTTPClient(client *http.Client) *GetTestRunsParams {
	return &GetTestRunsParams{
		HTTPClient: client,
	}
}

/* GetTestRunsParams contains all the parameters to send to the API endpoint
   for the get test runs operation.

   Typically these are written to a http.Request.
*/
type GetTestRunsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get test runs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTestRunsParams) WithDefaults() *GetTestRunsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get test runs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTestRunsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get test runs params
func (o *GetTestRunsParams) WithTimeout(timeout time.Duration) *GetTestRunsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get test runs params
func (o *GetTestRunsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get test runs params
func (o *GetTestRunsParams) WithContext(ctx context.Context) *GetTestRunsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get test runs params
func (o *GetTestRunsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get test runs params
func (o *GetTestRunsParams) WithHTTPClient(client *http.Client) *GetTestRunsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get test runs params
func (o *GetTestRunsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTestRunsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
