// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mayastor-e2e/tools/extended-test-framework/workload_monitor/swagger/models"
)

// GetTestPlansReader is a Reader for the GetTestPlans structure.
type GetTestPlansReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTestPlansReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTestPlansOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetTestPlansNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTestPlansOK creates a GetTestPlansOK with default headers values
func NewGetTestPlansOK() *GetTestPlansOK {
	return &GetTestPlansOK{}
}

/* GetTestPlansOK describes a response with status code 200, with default header values.

search results available and returned
*/
type GetTestPlansOK struct {
	Payload []*models.TestPlan
}

func (o *GetTestPlansOK) Error() string {
	return fmt.Sprintf("[GET /td/testplans][%d] getTestPlansOK  %+v", 200, o.Payload)
}
func (o *GetTestPlansOK) GetPayload() []*models.TestPlan {
	return o.Payload
}

func (o *GetTestPlansOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTestPlansNotFound creates a GetTestPlansNotFound with default headers values
func NewGetTestPlansNotFound() *GetTestPlansNotFound {
	return &GetTestPlansNotFound{}
}

/* GetTestPlansNotFound describes a response with status code 404, with default header values.

no matching Test Plan(s) found
*/
type GetTestPlansNotFound struct {
}

func (o *GetTestPlansNotFound) Error() string {
	return fmt.Sprintf("[GET /td/testplans][%d] getTestPlansNotFound ", 404)
}

func (o *GetTestPlansNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
