// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"mayastor-e2e/tools/extended-test-framework/workload_monitor/swagger/models"
)

// NewPutTestRunByIDParams creates a new PutTestRunByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutTestRunByIDParams() *PutTestRunByIDParams {
	return &PutTestRunByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutTestRunByIDParamsWithTimeout creates a new PutTestRunByIDParams object
// with the ability to set a timeout on a request.
func NewPutTestRunByIDParamsWithTimeout(timeout time.Duration) *PutTestRunByIDParams {
	return &PutTestRunByIDParams{
		timeout: timeout,
	}
}

// NewPutTestRunByIDParamsWithContext creates a new PutTestRunByIDParams object
// with the ability to set a context for a request.
func NewPutTestRunByIDParamsWithContext(ctx context.Context) *PutTestRunByIDParams {
	return &PutTestRunByIDParams{
		Context: ctx,
	}
}

// NewPutTestRunByIDParamsWithHTTPClient creates a new PutTestRunByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutTestRunByIDParamsWithHTTPClient(client *http.Client) *PutTestRunByIDParams {
	return &PutTestRunByIDParams{
		HTTPClient: client,
	}
}

/* PutTestRunByIDParams contains all the parameters to send to the API endpoint
   for the put test run by Id operation.

   Typically these are written to a http.Request.
*/
type PutTestRunByIDParams struct {

	// Body.
	Body *models.TestRunSpec

	/* ID.

	   Test Run id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put test run by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutTestRunByIDParams) WithDefaults() *PutTestRunByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put test run by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutTestRunByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put test run by Id params
func (o *PutTestRunByIDParams) WithTimeout(timeout time.Duration) *PutTestRunByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put test run by Id params
func (o *PutTestRunByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put test run by Id params
func (o *PutTestRunByIDParams) WithContext(ctx context.Context) *PutTestRunByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put test run by Id params
func (o *PutTestRunByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put test run by Id params
func (o *PutTestRunByIDParams) WithHTTPClient(client *http.Client) *PutTestRunByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put test run by Id params
func (o *PutTestRunByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put test run by Id params
func (o *PutTestRunByIDParams) WithBody(body *models.TestRunSpec) *PutTestRunByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put test run by Id params
func (o *PutTestRunByIDParams) SetBody(body *models.TestRunSpec) {
	o.Body = body
}

// WithID adds the id to the put test run by Id params
func (o *PutTestRunByIDParams) WithID(id string) *PutTestRunByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put test run by Id params
func (o *PutTestRunByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutTestRunByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
