status = [ "continuous-integration/jenkins/branch" ]
timeout_sec = 10000
required_approvals = 2
delete_merged_branches = true
block_labels = [ "DO NOT MERGE", "wip" ]
cut_body_after = "---"
committer.name = "mayastor-e2e-bors-ng"
committer.email = "mayastor-e2e-bors-ng@noreply.github.com"