// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mayastor-e2e/tools/extended-test-framework/test_director/models"
)

// DeleteTestPlansReader is a Reader for the DeleteTestPlans structure.
type DeleteTestPlansReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTestPlansReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteTestPlansOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteTestPlansOK creates a DeleteTestPlansOK with default headers values
func NewDeleteTestPlansOK() *DeleteTestPlansOK {
	return &DeleteTestPlansOK{}
}

/* DeleteTestPlansOK describes a response with status code 200, with default header values.

Returns deleted Test Plan count, which may be zero
*/
type DeleteTestPlansOK struct {
	Payload *models.RequestOutcome
}

func (o *DeleteTestPlansOK) Error() string {
	return fmt.Sprintf("[DELETE /td/testplans][%d] deleteTestPlansOK  %+v", 200, o.Payload)
}
func (o *DeleteTestPlansOK) GetPayload() *models.RequestOutcome {
	return o.Payload
}

func (o *DeleteTestPlansOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RequestOutcome)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
