// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTestRunByIDParams creates a new DeleteTestRunByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTestRunByIDParams() *DeleteTestRunByIDParams {
	return &DeleteTestRunByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTestRunByIDParamsWithTimeout creates a new DeleteTestRunByIDParams object
// with the ability to set a timeout on a request.
func NewDeleteTestRunByIDParamsWithTimeout(timeout time.Duration) *DeleteTestRunByIDParams {
	return &DeleteTestRunByIDParams{
		timeout: timeout,
	}
}

// NewDeleteTestRunByIDParamsWithContext creates a new DeleteTestRunByIDParams object
// with the ability to set a context for a request.
func NewDeleteTestRunByIDParamsWithContext(ctx context.Context) *DeleteTestRunByIDParams {
	return &DeleteTestRunByIDParams{
		Context: ctx,
	}
}

// NewDeleteTestRunByIDParamsWithHTTPClient creates a new DeleteTestRunByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTestRunByIDParamsWithHTTPClient(client *http.Client) *DeleteTestRunByIDParams {
	return &DeleteTestRunByIDParams{
		HTTPClient: client,
	}
}

/* DeleteTestRunByIDParams contains all the parameters to send to the API endpoint
   for the delete test run by Id operation.

   Typically these are written to a http.Request.
*/
type DeleteTestRunByIDParams struct {

	/* ID.

	   Test Plan Id

	   Format: Jira issue key
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete test run by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTestRunByIDParams) WithDefaults() *DeleteTestRunByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete test run by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTestRunByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete test run by Id params
func (o *DeleteTestRunByIDParams) WithTimeout(timeout time.Duration) *DeleteTestRunByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete test run by Id params
func (o *DeleteTestRunByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete test run by Id params
func (o *DeleteTestRunByIDParams) WithContext(ctx context.Context) *DeleteTestRunByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete test run by Id params
func (o *DeleteTestRunByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete test run by Id params
func (o *DeleteTestRunByIDParams) WithHTTPClient(client *http.Client) *DeleteTestRunByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete test run by Id params
func (o *DeleteTestRunByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete test run by Id params
func (o *DeleteTestRunByIDParams) WithID(id string) *DeleteTestRunByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete test run by Id params
func (o *DeleteTestRunByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTestRunByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
