// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTestPlanByIDParams creates a new DeleteTestPlanByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTestPlanByIDParams() *DeleteTestPlanByIDParams {
	return &DeleteTestPlanByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTestPlanByIDParamsWithTimeout creates a new DeleteTestPlanByIDParams object
// with the ability to set a timeout on a request.
func NewDeleteTestPlanByIDParamsWithTimeout(timeout time.Duration) *DeleteTestPlanByIDParams {
	return &DeleteTestPlanByIDParams{
		timeout: timeout,
	}
}

// NewDeleteTestPlanByIDParamsWithContext creates a new DeleteTestPlanByIDParams object
// with the ability to set a context for a request.
func NewDeleteTestPlanByIDParamsWithContext(ctx context.Context) *DeleteTestPlanByIDParams {
	return &DeleteTestPlanByIDParams{
		Context: ctx,
	}
}

// NewDeleteTestPlanByIDParamsWithHTTPClient creates a new DeleteTestPlanByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTestPlanByIDParamsWithHTTPClient(client *http.Client) *DeleteTestPlanByIDParams {
	return &DeleteTestPlanByIDParams{
		HTTPClient: client,
	}
}

/* DeleteTestPlanByIDParams contains all the parameters to send to the API endpoint
   for the delete test plan by Id operation.

   Typically these are written to a http.Request.
*/
type DeleteTestPlanByIDParams struct {

	/* ID.

	   Test Plan Id

	   Format: Jira issue key
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete test plan by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTestPlanByIDParams) WithDefaults() *DeleteTestPlanByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete test plan by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTestPlanByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete test plan by Id params
func (o *DeleteTestPlanByIDParams) WithTimeout(timeout time.Duration) *DeleteTestPlanByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete test plan by Id params
func (o *DeleteTestPlanByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete test plan by Id params
func (o *DeleteTestPlanByIDParams) WithContext(ctx context.Context) *DeleteTestPlanByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete test plan by Id params
func (o *DeleteTestPlanByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete test plan by Id params
func (o *DeleteTestPlanByIDParams) WithHTTPClient(client *http.Client) *DeleteTestPlanByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete test plan by Id params
func (o *DeleteTestPlanByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete test plan by Id params
func (o *DeleteTestPlanByIDParams) WithID(id string) *DeleteTestPlanByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete test plan by Id params
func (o *DeleteTestPlanByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTestPlanByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
