// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mayastor-e2e/tools/extended-test-framework/test_director/models"
)

// DeleteTestPlanByIDReader is a Reader for the DeleteTestPlanByID structure.
type DeleteTestPlanByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTestPlanByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteTestPlanByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteTestPlanByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteTestPlanByIDOK creates a DeleteTestPlanByIDOK with default headers values
func NewDeleteTestPlanByIDOK() *DeleteTestPlanByIDOK {
	return &DeleteTestPlanByIDOK{}
}

/* DeleteTestPlanByIDOK describes a response with status code 200, with default header values.

Returns deleted Test Plan
*/
type DeleteTestPlanByIDOK struct {
	Payload *models.TestPlan
}

func (o *DeleteTestPlanByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /td/testplans/{id}][%d] deleteTestPlanByIdOK  %+v", 200, o.Payload)
}
func (o *DeleteTestPlanByIDOK) GetPayload() *models.TestPlan {
	return o.Payload
}

func (o *DeleteTestPlanByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TestPlan)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteTestPlanByIDNotFound creates a DeleteTestPlanByIDNotFound with default headers values
func NewDeleteTestPlanByIDNotFound() *DeleteTestPlanByIDNotFound {
	return &DeleteTestPlanByIDNotFound{}
}

/* DeleteTestPlanByIDNotFound describes a response with status code 404, with default header values.

no matching Test Plan found
*/
type DeleteTestPlanByIDNotFound struct {
}

func (o *DeleteTestPlanByIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /td/testplans/{id}][%d] deleteTestPlanByIdNotFound ", 404)
}

func (o *DeleteTestPlanByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
