// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"mayastor-e2e/tools/extended-test-framework/test_director/models"
)

// NewPutTestPlanByIDParams creates a new PutTestPlanByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutTestPlanByIDParams() *PutTestPlanByIDParams {
	return &PutTestPlanByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutTestPlanByIDParamsWithTimeout creates a new PutTestPlanByIDParams object
// with the ability to set a timeout on a request.
func NewPutTestPlanByIDParamsWithTimeout(timeout time.Duration) *PutTestPlanByIDParams {
	return &PutTestPlanByIDParams{
		timeout: timeout,
	}
}

// NewPutTestPlanByIDParamsWithContext creates a new PutTestPlanByIDParams object
// with the ability to set a context for a request.
func NewPutTestPlanByIDParamsWithContext(ctx context.Context) *PutTestPlanByIDParams {
	return &PutTestPlanByIDParams{
		Context: ctx,
	}
}

// NewPutTestPlanByIDParamsWithHTTPClient creates a new PutTestPlanByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutTestPlanByIDParamsWithHTTPClient(client *http.Client) *PutTestPlanByIDParams {
	return &PutTestPlanByIDParams{
		HTTPClient: client,
	}
}

/* PutTestPlanByIDParams contains all the parameters to send to the API endpoint
   for the put test plan by Id operation.

   Typically these are written to a http.Request.
*/
type PutTestPlanByIDParams struct {

	// Body.
	Body *models.TestPlanSpec

	/* ID.

	   Test Plan Id

	   Format: Jira issue key
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put test plan by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutTestPlanByIDParams) WithDefaults() *PutTestPlanByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put test plan by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutTestPlanByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put test plan by Id params
func (o *PutTestPlanByIDParams) WithTimeout(timeout time.Duration) *PutTestPlanByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put test plan by Id params
func (o *PutTestPlanByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put test plan by Id params
func (o *PutTestPlanByIDParams) WithContext(ctx context.Context) *PutTestPlanByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put test plan by Id params
func (o *PutTestPlanByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put test plan by Id params
func (o *PutTestPlanByIDParams) WithHTTPClient(client *http.Client) *PutTestPlanByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put test plan by Id params
func (o *PutTestPlanByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put test plan by Id params
func (o *PutTestPlanByIDParams) WithBody(body *models.TestPlanSpec) *PutTestPlanByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put test plan by Id params
func (o *PutTestPlanByIDParams) SetBody(body *models.TestPlanSpec) {
	o.Body = body
}

// WithID adds the id to the put test plan by Id params
func (o *PutTestPlanByIDParams) WithID(id string) *PutTestPlanByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put test plan by Id params
func (o *PutTestPlanByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutTestPlanByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
