configName: "steady_state"
registry: ci-registry.mayastor-ci.mayadata.io
imageTag: "nightly-stable"
poolDevice: "/dev/sdb"
test: "steady_state"
e2eFioImage: mayadata/e2e-fio
replicaCount: 2
steadyStateTest:
  replicas: 2
  duration: 60m

