#!/usr/bin/env groovy


def Common() {
    def common = load "./pipelines/common2/common.groovy"
    return common
}

def image_tag = ""
def test_job_params = [
    [ $class: 'BooleanParameterValue', name: "build_images",   value: false ],
    [ $class: 'StringParameterValue',  name: "image_tag",      value: image_tag ],
    [ $class: 'StringParameterValue',  name: "xray_test_plan", value: "MQ-2864" ],
]

//The five time-and-date fields are as follows:
//minute (0-59), hour (0-23, 0 = midnight), day (1-31), month (1-12), weekday (0-6, 0 = Sunday).
// Daily => Monday to Friday. On Saturday and Sunday this pipeline will be
// invoked by the weekend pipeline.
String cron_schedule = "H 12 * * 6,0"

pipeline {
    agent any
    options {
      timeout(time: 12, unit: 'HOURS')
      buildDiscarder(logRotator(numToKeepStr: '365', artifactNumToKeepStr: '365'))
    }
    triggers {
      cron(cron_schedule)
    }
    stages {
        stage('build image') {
            steps {
                script {
                    image_tag = 'develop-' + Common().GetTestTag()
                    test_job_params.add(
                        [ $class: 'StringParameterValue',  name: "image_tag",      value: image_tag ]
                        )
                    def build_job_params = [
                        [ $class: 'StringParameterValue',  name: "dataplaneBranch",    value: "develop" ],
                        [ $class: 'StringParameterValue',  name: "controlplaneBranch", value: "develop" ],
                        [ $class: 'BooleanParameterValue', name: "build_images",       value: true ],
                        [ $class: 'StringParameterValue',  name: "image_tag",          value: image_tag ]
                    ]
                    build(
                       job: "generic-system-test/develop",
                       propagate: true,
                       wait: true,
                       parameters: build_job_params
                   )
                }
            }
        }
        stage('test image on k8s-1.21') {
            steps {
                script {
                    build(
                       job: "mayastor-ubuntu20-04-lts-k8s-1.21/develop",
                       propagate: false,
                       wait: true,
                       parameters: test_job_params
                   )
                }
            }
        }
        stage('test image on k8s-1.22') {
            steps {
                script {
                    build(
                       job: "mayastor-ubuntu20-04-lts-k8s-1.22/develop",
                       propagate: false,
                       wait: true,
                       parameters: test_job_params
                   )
                }
            }
        }
        stage('test image on k8s-1.23') {
            steps {
                script {
                    build(
                       job: "mayastor-ubuntu20-04-lts-k8s-1.23/develop",
                       propagate: false,
                       wait: true,
                       parameters: test_job_params
                   )
                }
            }
        }
    }
}
