// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mayastor-e2e/tools/extended-test-framework/test_director/models"
)

// DeleteTestPlanByIDOKCode is the HTTP code returned for type DeleteTestPlanByIDOK
const DeleteTestPlanByIDOKCode int = 200

/*DeleteTestPlanByIDOK Returns deleted Test Plan

swagger:response deleteTestPlanByIdOK
*/
type DeleteTestPlanByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.TestPlan `json:"body,omitempty"`
}

// NewDeleteTestPlanByIDOK creates DeleteTestPlanByIDOK with default headers values
func NewDeleteTestPlanByIDOK() *DeleteTestPlanByIDOK {

	return &DeleteTestPlanByIDOK{}
}

// WithPayload adds the payload to the delete test plan by Id o k response
func (o *DeleteTestPlanByIDOK) WithPayload(payload *models.TestPlan) *DeleteTestPlanByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete test plan by Id o k response
func (o *DeleteTestPlanByIDOK) SetPayload(payload *models.TestPlan) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTestPlanByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteTestPlanByIDNotFoundCode is the HTTP code returned for type DeleteTestPlanByIDNotFound
const DeleteTestPlanByIDNotFoundCode int = 404

/*DeleteTestPlanByIDNotFound no matching Test Plan found

swagger:response deleteTestPlanByIdNotFound
*/
type DeleteTestPlanByIDNotFound struct {
}

// NewDeleteTestPlanByIDNotFound creates DeleteTestPlanByIDNotFound with default headers values
func NewDeleteTestPlanByIDNotFound() *DeleteTestPlanByIDNotFound {

	return &DeleteTestPlanByIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteTestPlanByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
