// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mayastor-e2e/tools/extended-test-framework/test_director/models"
)

// DeleteTestRunByIDOKCode is the HTTP code returned for type DeleteTestRunByIDOK
const DeleteTestRunByIDOKCode int = 200

/*DeleteTestRunByIDOK Returns the deleted Test Run

swagger:response deleteTestRunByIdOK
*/
type DeleteTestRunByIDOK struct {

	/*
	  In: Body
	*/
	Payload []*models.TestRun `json:"body,omitempty"`
}

// NewDeleteTestRunByIDOK creates DeleteTestRunByIDOK with default headers values
func NewDeleteTestRunByIDOK() *DeleteTestRunByIDOK {

	return &DeleteTestRunByIDOK{}
}

// WithPayload adds the payload to the delete test run by Id o k response
func (o *DeleteTestRunByIDOK) WithPayload(payload []*models.TestRun) *DeleteTestRunByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete test run by Id o k response
func (o *DeleteTestRunByIDOK) SetPayload(payload []*models.TestRun) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTestRunByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.TestRun, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteTestRunByIDNotFoundCode is the HTTP code returned for type DeleteTestRunByIDNotFound
const DeleteTestRunByIDNotFoundCode int = 404

/*DeleteTestRunByIDNotFound Test Run not found

swagger:response deleteTestRunByIdNotFound
*/
type DeleteTestRunByIDNotFound struct {
}

// NewDeleteTestRunByIDNotFound creates DeleteTestRunByIDNotFound with default headers values
func NewDeleteTestRunByIDNotFound() *DeleteTestRunByIDNotFound {

	return &DeleteTestRunByIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteTestRunByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
