apiVersion: v1
kind: Service
metadata:
  name: test-director
spec:
  type: NodePort
  selector:
    app: test-director
  ports:
    - port: 8080
      #targetPort: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: test-director
  labels:
    app: test-director
spec:
  containers:
    - name: test-director
      image: ci-registry.mayastor-ci.mayadata.io/mayadata/test_director:mhajek
      imagePullPolicy: Always
      args:
        - "/test_director"
      env:
      - name: XRAY_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: test-director-secret
            key: xray_client_id
      - name: XRAY_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: test-director-secret
            key: xray_client_secret
      - name: JIRA_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: test-director-secret
            key: jira_api_token
      - name: SLACK_WEB_HOOK
        valueFrom:
          secretKeyRef:
            name: test-director-secret
            key: slack_web_hook
      ports:
        - containerPort: 8080
          protocol: "TCP"
          name: test-director
  restartPolicy: OnFailure

