
def e2e_environment="hcloud-kubeadm"
def e2e_build_cluster_job='k8s-build-cluster' // Jenkins job to build cluster

def GetClusterAdminConf(e2e_build_cluster_job, e2e_environment, k8s_job_number) {
  // FIXME(arne-rusek): move hcloud's config to top-level dir in TF scripts
  sh """
    mkdir -p "${e2e_environment}/modules/k8s/secrets"
  """

  copyArtifacts(
    projectName: "${e2e_build_cluster_job}",
    selector: specific("${k8s_job_number}"),
    filter: "${e2e_environment}/modules/k8s/secrets/admin.conf",
    target: "",
    fingerprintArtifacts: true
  )
  sh 'kubectl get nodes -o wide'
}

pipeline {
    agent { label 'nixos' }
    parameters {
        run(
            name:'BUILD',
            projectName: 'k8s-build-cluster',
            description: 'Selects cluster to use.'
        )
        booleanParam(name: 'node_correct', defaultValue: false,  description: 'Is the above cluster correct? <br>It must have mayastor installed and a node reserved for ETFW. <br> Is the cluster listed in the keep-clusters list in Jenkins? Otherwise it will be deleted after 1-2 days.<br> See README.md.')
        choice(choices: ['steady_state', 'non_steady_state', 'non_steady_state_multi_vols', 'replica_perturbation'], name: 'test', description: 'Select which test to run')
        string(defaultValue: 'MQ-2352', name: 'plan', description: 'Test plan to receive test runs')
        string(defaultValue: '10m', name: 'duration', trim: true, description: 'Run duration, use units h, m and s')
        booleanParam(name: 'cluster_dump', defaultValue: false,  description: 'Obtain and archive the cluster logs')
    }

    stages {
        stage('confirm') {
            steps {
                script {
                    if (params.node_correct != true) {
                        error 'cluster not confirmed as correct'
                    }
                }
            }
        }
        stage('run the test') {
            environment {
                KUBECONFIG = "${env.WORKSPACE}/${e2e_environment}/modules/k8s/secrets/admin.conf"
            }
            steps {
                script {
                    GetClusterAdminConf("${BUILD_JOBNAME}", e2e_environment, "${BUILD_NUMBER}")
                    // cluster should have one node dedicated to etfw pods
                    def rc = sh(script: 'kubectl describe nodes | grep openebs.io/role=mayastor-e2e:NoExecute', returnStatus: true)
                    if (rc != 0) {
                        error "Failed, cluster not labelled for extended-test-framework"
                    }
                    withCredentials([file(credentialsId: 'SEALED_SECRET_YAML', variable: 'file')]) {
                 	cmd = "cd src/tools/extended-test-framework/scripts && ./deploy.sh -t \"${params.test}\" -p \"${params.plan}\" -d \"${params.duration}\" -s \"${file}\" && ./wait.sh"
                    	sh "nix-shell --run '${cmd}'"
		    }

                }
            }
            post {
                always {
                    script {
                        sh 'mkdir -p ./artifacts/logs/etfw'
                        sh 'mkdir -p ./artifacts/logs/cluster'

                        sh 'kubectl logs -n mayastor-e2e test-conductor > ./artifacts/logs/etfw/test_conductor.log'
                        sh 'kubectl logs -n mayastor-e2e test-director > ./artifacts/logs/etfw/test_director.log'
                        sh 'kubectl logs -n mayastor-e2e workload-monitor > ./artifacts/logs/etfw/workload_monitor.log'

                        if (params.cluster_dump == true) {
                            sh './scripts/e2e-cluster-dump.sh --destdir ./artifacts/logs/cluster'
                        }
                        archiveArtifacts 'artifacts/**/*.*'

                        sh 'rm -rf ./artifacts'

                        // remove the ETFW pods
                        sh "nix-shell --run 'cd src/tools/extended-test-framework/scripts && ./deploy.sh -r' "
                    }
                }
            }
        }
    }
}

