// Code generated by go-swagger; DO NOT EDIT.

package workload_monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mayastor-e2e/tools/extended-test-framework/test_director/models"
)

// DeleteWorkloadsByRegistrantOKCode is the HTTP code returned for type DeleteWorkloadsByRegistrantOK
const DeleteWorkloadsByRegistrantOKCode int = 200

/*DeleteWorkloadsByRegistrantOK Workload(s) deleted

swagger:response deleteWorkloadsByRegistrantOK
*/
type DeleteWorkloadsByRegistrantOK struct {

	/*
	  In: Body
	*/
	Payload *models.RequestOutcome `json:"body,omitempty"`
}

// NewDeleteWorkloadsByRegistrantOK creates DeleteWorkloadsByRegistrantOK with default headers values
func NewDeleteWorkloadsByRegistrantOK() *DeleteWorkloadsByRegistrantOK {

	return &DeleteWorkloadsByRegistrantOK{}
}

// WithPayload adds the payload to the delete workloads by registrant o k response
func (o *DeleteWorkloadsByRegistrantOK) WithPayload(payload *models.RequestOutcome) *DeleteWorkloadsByRegistrantOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete workloads by registrant o k response
func (o *DeleteWorkloadsByRegistrantOK) SetPayload(payload *models.RequestOutcome) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWorkloadsByRegistrantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteWorkloadsByRegistrantBadRequestCode is the HTTP code returned for type DeleteWorkloadsByRegistrantBadRequest
const DeleteWorkloadsByRegistrantBadRequestCode int = 400

/*DeleteWorkloadsByRegistrantBadRequest Bad request (malformed/invalid resource id)

swagger:response deleteWorkloadsByRegistrantBadRequest
*/
type DeleteWorkloadsByRegistrantBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.RequestOutcome `json:"body,omitempty"`
}

// NewDeleteWorkloadsByRegistrantBadRequest creates DeleteWorkloadsByRegistrantBadRequest with default headers values
func NewDeleteWorkloadsByRegistrantBadRequest() *DeleteWorkloadsByRegistrantBadRequest {

	return &DeleteWorkloadsByRegistrantBadRequest{}
}

// WithPayload adds the payload to the delete workloads by registrant bad request response
func (o *DeleteWorkloadsByRegistrantBadRequest) WithPayload(payload *models.RequestOutcome) *DeleteWorkloadsByRegistrantBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete workloads by registrant bad request response
func (o *DeleteWorkloadsByRegistrantBadRequest) SetPayload(payload *models.RequestOutcome) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWorkloadsByRegistrantBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteWorkloadsByRegistrantNotFoundCode is the HTTP code returned for type DeleteWorkloadsByRegistrantNotFound
const DeleteWorkloadsByRegistrantNotFoundCode int = 404

/*DeleteWorkloadsByRegistrantNotFound resource not found

swagger:response deleteWorkloadsByRegistrantNotFound
*/
type DeleteWorkloadsByRegistrantNotFound struct {
}

// NewDeleteWorkloadsByRegistrantNotFound creates DeleteWorkloadsByRegistrantNotFound with default headers values
func NewDeleteWorkloadsByRegistrantNotFound() *DeleteWorkloadsByRegistrantNotFound {

	return &DeleteWorkloadsByRegistrantNotFound{}
}

// WriteResponse to the client
func (o *DeleteWorkloadsByRegistrantNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
