// Code generated by go-swagger; DO NOT EDIT.

package workload_monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"mayastor-e2e/tools/extended-test-framework/test_director/models"
)

// DeleteWorkloadByRegistrantOKCode is the HTTP code returned for type DeleteWorkloadByRegistrantOK
const DeleteWorkloadByRegistrantOKCode int = 200

/*DeleteWorkloadByRegistrantOK Workload deleted

swagger:response deleteWorkloadByRegistrantOK
*/
type DeleteWorkloadByRegistrantOK struct {

	/*
	  In: Body
	*/
	Payload *models.Workload `json:"body,omitempty"`
}

// NewDeleteWorkloadByRegistrantOK creates DeleteWorkloadByRegistrantOK with default headers values
func NewDeleteWorkloadByRegistrantOK() *DeleteWorkloadByRegistrantOK {

	return &DeleteWorkloadByRegistrantOK{}
}

// WithPayload adds the payload to the delete workload by registrant o k response
func (o *DeleteWorkloadByRegistrantOK) WithPayload(payload *models.Workload) *DeleteWorkloadByRegistrantOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete workload by registrant o k response
func (o *DeleteWorkloadByRegistrantOK) SetPayload(payload *models.Workload) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWorkloadByRegistrantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteWorkloadByRegistrantBadRequestCode is the HTTP code returned for type DeleteWorkloadByRegistrantBadRequest
const DeleteWorkloadByRegistrantBadRequestCode int = 400

/*DeleteWorkloadByRegistrantBadRequest Bad request (malformed/invalid resource id)

swagger:response deleteWorkloadByRegistrantBadRequest
*/
type DeleteWorkloadByRegistrantBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.RequestOutcome `json:"body,omitempty"`
}

// NewDeleteWorkloadByRegistrantBadRequest creates DeleteWorkloadByRegistrantBadRequest with default headers values
func NewDeleteWorkloadByRegistrantBadRequest() *DeleteWorkloadByRegistrantBadRequest {

	return &DeleteWorkloadByRegistrantBadRequest{}
}

// WithPayload adds the payload to the delete workload by registrant bad request response
func (o *DeleteWorkloadByRegistrantBadRequest) WithPayload(payload *models.RequestOutcome) *DeleteWorkloadByRegistrantBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete workload by registrant bad request response
func (o *DeleteWorkloadByRegistrantBadRequest) SetPayload(payload *models.RequestOutcome) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWorkloadByRegistrantBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteWorkloadByRegistrantNotFoundCode is the HTTP code returned for type DeleteWorkloadByRegistrantNotFound
const DeleteWorkloadByRegistrantNotFoundCode int = 404

/*DeleteWorkloadByRegistrantNotFound resource not found

swagger:response deleteWorkloadByRegistrantNotFound
*/
type DeleteWorkloadByRegistrantNotFound struct {
}

// NewDeleteWorkloadByRegistrantNotFound creates DeleteWorkloadByRegistrantNotFound with default headers values
func NewDeleteWorkloadByRegistrantNotFound() *DeleteWorkloadByRegistrantNotFound {

	return &DeleteWorkloadByRegistrantNotFound{}
}

// WriteResponse to the client
func (o *DeleteWorkloadByRegistrantNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
