// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TestPlanSpec test plan spec
//
// swagger:model TestPlanSpec
type TestPlanSpec struct {

	// assigned user to the test plan/owner
	// Example: John Doe
	Assignee string `json:"assignee,omitempty"`

	// Jira id representation
	JiraID string `json:"jiraId,omitempty"`

	// display name
	// Example: Nightly Stable Test Plan
	Name string `json:"name,omitempty"`

	// status
	// Required: true
	Status *TestPlanStatusEnum `json:"status"`

	// tests
	Tests []*Test `json:"tests"`
}

// Validate validates this test plan spec
func (m *TestPlanSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTests(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TestPlanSpec) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *TestPlanSpec) validateTests(formats strfmt.Registry) error {
	if swag.IsZero(m.Tests) { // not required
		return nil
	}

	for i := 0; i < len(m.Tests); i++ {
		if swag.IsZero(m.Tests[i]) { // not required
			continue
		}

		if m.Tests[i] != nil {
			if err := m.Tests[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tests" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this test plan spec based on the context it is used
func (m *TestPlanSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTests(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TestPlanSpec) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.Status != nil {
		if err := m.Status.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *TestPlanSpec) contextValidateTests(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Tests); i++ {

		if m.Tests[i] != nil {
			if err := m.Tests[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tests" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TestPlanSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TestPlanSpec) UnmarshalBinary(b []byte) error {
	var res TestPlanSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
