// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Workload workload
//
// swagger:model Workload
type Workload struct {

	// metadata.uid of workload pod
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// name
	Name RFC1123Label `json:"name,omitempty"`

	// namespace
	Namespace RFC1123Label `json:"namespace,omitempty"`

	WorkloadSpec
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Workload) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		ID strfmt.UUID `json:"id,omitempty"`

		Name RFC1123Label `json:"name,omitempty"`

		Namespace RFC1123Label `json:"namespace,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.ID = dataAO0.ID

	m.Name = dataAO0.Name

	m.Namespace = dataAO0.Namespace

	// AO1
	var aO1 WorkloadSpec
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.WorkloadSpec = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Workload) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		ID strfmt.UUID `json:"id,omitempty"`

		Name RFC1123Label `json:"name,omitempty"`

		Namespace RFC1123Label `json:"namespace,omitempty"`
	}

	dataAO0.ID = m.ID

	dataAO0.Name = m.Name

	dataAO0.Namespace = m.Namespace

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)

	aO1, err := swag.WriteJSON(m.WorkloadSpec)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this workload
func (m *Workload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNamespace(formats); err != nil {
		res = append(res, err)
	}

	// validation for a type composition with WorkloadSpec
	if err := m.WorkloadSpec.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Workload) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Workload) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := m.Name.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("name")
		}
		return err
	}

	return nil
}

func (m *Workload) validateNamespace(formats strfmt.Registry) error {

	if swag.IsZero(m.Namespace) { // not required
		return nil
	}

	if err := m.Namespace.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("namespace")
		}
		return err
	}

	return nil
}

// ContextValidate validate this workload based on the context it is used
func (m *Workload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNamespace(ctx, formats); err != nil {
		res = append(res, err)
	}

	// validation for a type composition with WorkloadSpec
	if err := m.WorkloadSpec.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Workload) contextValidateName(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Name.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("name")
		}
		return err
	}

	return nil
}

func (m *Workload) contextValidateNamespace(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Namespace.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("namespace")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Workload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Workload) UnmarshalBinary(b []byte) error {
	var res Workload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
