// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// RFC1123Label kubernetes label name conforming to RFC1123
//
// swagger:model RFC1123Label
type RFC1123Label string

// Validate validates this r f c1123 label
func (m RFC1123Label) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Pattern("", "body", string(m), `^[a-z0-9][a-z0-9\-]{0,61}[a-z0-9]{1}`); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this r f c1123 label based on context it is used
func (m RFC1123Label) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
