// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTestPlanByIDHandlerFunc turns a function with the right signature into a get test plan by Id handler
type GetTestPlanByIDHandlerFunc func(GetTestPlanByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTestPlanByIDHandlerFunc) Handle(params GetTestPlanByIDParams) middleware.Responder {
	return fn(params)
}

// GetTestPlanByIDHandler interface for that can handle valid get test plan by Id params
type GetTestPlanByIDHandler interface {
	Handle(GetTestPlanByIDParams) middleware.Responder
}

// NewGetTestPlanByID creates a new http.Handler for the get test plan by Id operation
func NewGetTestPlanByID(ctx *middleware.Context, handler GetTestPlanByIDHandler) *GetTestPlanByID {
	return &GetTestPlanByID{Context: ctx, Handler: handler}
}

/* GetTestPlanByID swagger:route GET /td/testplans/{id} test-director getTestPlanById

searches for a specific Test Plan by its id

*/
type GetTestPlanByID struct {
	Context *middleware.Context
	Handler GetTestPlanByIDHandler
}

func (o *GetTestPlanByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTestPlanByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
