// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Event event
//
// swagger:model Event
type Event struct {

	// id
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// logged date time
	// Format: date-time
	LoggedDateTime strfmt.DateTime `json:"loggedDateTime,omitempty"`

	EventSpec
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Event) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		ID strfmt.UUID `json:"id,omitempty"`

		LoggedDateTime strfmt.DateTime `json:"loggedDateTime,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.ID = dataAO0.ID

	m.LoggedDateTime = dataAO0.LoggedDateTime

	// AO1
	var aO1 EventSpec
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.EventSpec = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Event) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		ID strfmt.UUID `json:"id,omitempty"`

		LoggedDateTime strfmt.DateTime `json:"loggedDateTime,omitempty"`
	}

	dataAO0.ID = m.ID

	dataAO0.LoggedDateTime = m.LoggedDateTime

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)

	aO1, err := swag.WriteJSON(m.EventSpec)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this event
func (m *Event) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLoggedDateTime(formats); err != nil {
		res = append(res, err)
	}

	// validation for a type composition with EventSpec
	if err := m.EventSpec.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Event) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Event) validateLoggedDateTime(formats strfmt.Registry) error {

	if swag.IsZero(m.LoggedDateTime) { // not required
		return nil
	}

	if err := validate.FormatOf("loggedDateTime", "body", "date-time", m.LoggedDateTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this event based on the context it is used
func (m *Event) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with EventSpec
	if err := m.EventSpec.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Event) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Event) UnmarshalBinary(b []byte) error {
	var res Event
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
