// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// TestRunStatusEnum test run status enum
//
// swagger:model TestRunStatusEnum
type TestRunStatusEnum string

func NewTestRunStatusEnum(value TestRunStatusEnum) *TestRunStatusEnum {
	v := value
	return &v
}

const (

	// TestRunStatusEnumTODO captures enum value "TO DO"
	TestRunStatusEnumTODO TestRunStatusEnum = "TO DO"

	// TestRunStatusEnumEXECUTING captures enum value "EXECUTING"
	TestRunStatusEnumEXECUTING TestRunStatusEnum = "EXECUTING"

	// TestRunStatusEnumPASSED captures enum value "PASSED"
	TestRunStatusEnumPASSED TestRunStatusEnum = "PASSED"

	// TestRunStatusEnumFAILED captures enum value "FAILED"
	TestRunStatusEnumFAILED TestRunStatusEnum = "FAILED"
)

// for schema
var testRunStatusEnumEnum []interface{}

func init() {
	var res []TestRunStatusEnum
	if err := json.Unmarshal([]byte(`["TO DO","EXECUTING","PASSED","FAILED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		testRunStatusEnumEnum = append(testRunStatusEnumEnum, v)
	}
}

func (m TestRunStatusEnum) validateTestRunStatusEnumEnum(path, location string, value TestRunStatusEnum) error {
	if err := validate.EnumCase(path, location, value, testRunStatusEnumEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this test run status enum
func (m TestRunStatusEnum) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTestRunStatusEnumEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this test run status enum based on context it is used
func (m TestRunStatusEnum) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
