apiVersion: v1
kind: Service
metadata:
  name: test-registry
spec:
  selector:
    app: test-registry
  type: NodePort
  ports:
  - name: registry
    protocol: TCP
    port: 5000
    nodePort: 30291
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-registry
  template:
    metadata:
      labels:
        app: test-registry
    spec:
      containers:
      - name: test-registry
        image: registry:2
