// Code generated by go-swagger; DO NOT EDIT.

package workload_monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mayastor-e2e/tools/extended-test-framework/test_director/models"
)

// DeleteWorkloadByRegistrantReader is a Reader for the DeleteWorkloadByRegistrant structure.
type DeleteWorkloadByRegistrantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteWorkloadByRegistrantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteWorkloadByRegistrantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteWorkloadByRegistrantBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteWorkloadByRegistrantNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteWorkloadByRegistrantOK creates a DeleteWorkloadByRegistrantOK with default headers values
func NewDeleteWorkloadByRegistrantOK() *DeleteWorkloadByRegistrantOK {
	return &DeleteWorkloadByRegistrantOK{}
}

/* DeleteWorkloadByRegistrantOK describes a response with status code 200, with default header values.

Workload deleted
*/
type DeleteWorkloadByRegistrantOK struct {
	Payload *models.Workload
}

func (o *DeleteWorkloadByRegistrantOK) Error() string {
	return fmt.Sprintf("[DELETE /wm/registrants/{rid}/workloads/{wid}][%d] deleteWorkloadByRegistrantOK  %+v", 200, o.Payload)
}
func (o *DeleteWorkloadByRegistrantOK) GetPayload() *models.Workload {
	return o.Payload
}

func (o *DeleteWorkloadByRegistrantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Workload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteWorkloadByRegistrantBadRequest creates a DeleteWorkloadByRegistrantBadRequest with default headers values
func NewDeleteWorkloadByRegistrantBadRequest() *DeleteWorkloadByRegistrantBadRequest {
	return &DeleteWorkloadByRegistrantBadRequest{}
}

/* DeleteWorkloadByRegistrantBadRequest describes a response with status code 400, with default header values.

Bad request (malformed/invalid resource id)
*/
type DeleteWorkloadByRegistrantBadRequest struct {
	Payload *models.RequestOutcome
}

func (o *DeleteWorkloadByRegistrantBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /wm/registrants/{rid}/workloads/{wid}][%d] deleteWorkloadByRegistrantBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteWorkloadByRegistrantBadRequest) GetPayload() *models.RequestOutcome {
	return o.Payload
}

func (o *DeleteWorkloadByRegistrantBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RequestOutcome)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteWorkloadByRegistrantNotFound creates a DeleteWorkloadByRegistrantNotFound with default headers values
func NewDeleteWorkloadByRegistrantNotFound() *DeleteWorkloadByRegistrantNotFound {
	return &DeleteWorkloadByRegistrantNotFound{}
}

/* DeleteWorkloadByRegistrantNotFound describes a response with status code 404, with default header values.

resource not found
*/
type DeleteWorkloadByRegistrantNotFound struct {
}

func (o *DeleteWorkloadByRegistrantNotFound) Error() string {
	return fmt.Sprintf("[DELETE /wm/registrants/{rid}/workloads/{wid}][%d] deleteWorkloadByRegistrantNotFound ", 404)
}

func (o *DeleteWorkloadByRegistrantNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
