// Code generated by go-swagger; DO NOT EDIT.

package workload_monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"mayastor-e2e/tools/extended-test-framework/test_director/models"
)

// NewPutRegistrantParams creates a new PutRegistrantParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutRegistrantParams() *PutRegistrantParams {
	return &PutRegistrantParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutRegistrantParamsWithTimeout creates a new PutRegistrantParams object
// with the ability to set a timeout on a request.
func NewPutRegistrantParamsWithTimeout(timeout time.Duration) *PutRegistrantParams {
	return &PutRegistrantParams{
		timeout: timeout,
	}
}

// NewPutRegistrantParamsWithContext creates a new PutRegistrantParams object
// with the ability to set a context for a request.
func NewPutRegistrantParamsWithContext(ctx context.Context) *PutRegistrantParams {
	return &PutRegistrantParams{
		Context: ctx,
	}
}

// NewPutRegistrantParamsWithHTTPClient creates a new PutRegistrantParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutRegistrantParamsWithHTTPClient(client *http.Client) *PutRegistrantParams {
	return &PutRegistrantParams{
		HTTPClient: client,
	}
}

/* PutRegistrantParams contains all the parameters to send to the API endpoint
   for the put registrant operation.

   Typically these are written to a http.Request.
*/
type PutRegistrantParams struct {

	/* Rid.

	   registrant uid
	*/
	Rid *models.Registrant

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put registrant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutRegistrantParams) WithDefaults() *PutRegistrantParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put registrant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutRegistrantParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put registrant params
func (o *PutRegistrantParams) WithTimeout(timeout time.Duration) *PutRegistrantParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put registrant params
func (o *PutRegistrantParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put registrant params
func (o *PutRegistrantParams) WithContext(ctx context.Context) *PutRegistrantParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put registrant params
func (o *PutRegistrantParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put registrant params
func (o *PutRegistrantParams) WithHTTPClient(client *http.Client) *PutRegistrantParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put registrant params
func (o *PutRegistrantParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRid adds the rid to the put registrant params
func (o *PutRegistrantParams) WithRid(rid *models.Registrant) *PutRegistrantParams {
	o.SetRid(rid)
	return o
}

// SetRid adds the rid to the put registrant params
func (o *PutRegistrantParams) SetRid(rid *models.Registrant) {
	o.Rid = rid
}

// WriteToRequest writes these params to a swagger request
func (o *PutRegistrantParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Rid != nil {
		if err := r.SetBodyParam(o.Rid); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
