apiVersion: v1
kind: Service
metadata:
  name: test-director
  namespace: mayastor-e2e
spec:
  type: NodePort
  selector:
    app: test-director
  ports:
    - port: 8080
      #targetPort: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: test-director
  namespace: mayastor-e2e
  labels:
    app: test-director
spec:
  containers:
    - name: test-director
      image: ci-registry.mayastor-ci.mayadata.io/mayadata/test_director:latest
      imagePullPolicy: Always
      args:
        - "/test_director"
      env:
      - name: PORT
        value: "8080"
      - name: HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      ports:
        - containerPort: 8080
          protocol: "TCP"
          name: test-dir
  restartPolicy: Never

