apiVersion: v1
kind: Service
metadata:
  name: workload-monitor
  namespace: mayastor-e2e
spec:
  type: NodePort
  selector:
    app: workload-monitor
  ports:
    - port: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-monitor-sa
  namespace: mayastor-e2e
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workload-monitor-cr
  namespace: mayastor-e2e
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workload-monitor-crb
  namespace: mayastor-e2e
subjects:
  - kind: ServiceAccount
    name: workload-monitor-sa
    namespace: mayastor-e2e
roleRef:
  kind: ClusterRole
  name: workload-monitor-cr
  apiGroup: rbac.authorization.k8s.io
---

kind: Pod
apiVersion: v1
metadata:
  name: workload-monitor
  namespace: mayastor-e2e
  labels:
    app: workload-monitor
spec:
  containers:
    - name: workload-monitor
      image: ci-registry.mayastor-ci.mayadata.io/mayadata/workload_monitor:latest
      args:
        - "/workload_monitor"
      env:
      - name: PORT
        value: "8080"
      - name: HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      ports:
        - containerPort: 8080
          protocol: "TCP"
          name: test-monitor
  restartPolicy: Never
  serviceAccountName: workload-monitor-sa


