// Code generated by go-swagger; DO NOT EDIT.

package workload_monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteWorkloadsByRegistrantHandlerFunc turns a function with the right signature into a delete workloads by registrant handler
type DeleteWorkloadsByRegistrantHandlerFunc func(DeleteWorkloadsByRegistrantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteWorkloadsByRegistrantHandlerFunc) Handle(params DeleteWorkloadsByRegistrantParams) middleware.Responder {
	return fn(params)
}

// DeleteWorkloadsByRegistrantHandler interface for that can handle valid delete workloads by registrant params
type DeleteWorkloadsByRegistrantHandler interface {
	Handle(DeleteWorkloadsByRegistrantParams) middleware.Responder
}

// NewDeleteWorkloadsByRegistrant creates a new http.Handler for the delete workloads by registrant operation
func NewDeleteWorkloadsByRegistrant(ctx *middleware.Context, handler DeleteWorkloadsByRegistrantHandler) *DeleteWorkloadsByRegistrant {
	return &DeleteWorkloadsByRegistrant{Context: ctx, Handler: handler}
}

/* DeleteWorkloadsByRegistrant swagger:route DELETE /wm/registrants/{rid} workload-monitor deleteWorkloadsByRegistrant

deletes all workloads registered by the specified registrant

*/
type DeleteWorkloadsByRegistrant struct {
	Context *middleware.Context
	Handler DeleteWorkloadsByRegistrantHandler
}

func (o *DeleteWorkloadsByRegistrant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteWorkloadsByRegistrantParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
