# This configuration is for testing changes made to mayastor-e2e
# and is used for mayastor-e2e CI runs
# Defining feature is that long running tests have attenuated durations
configName: e2e_ci
pvcstress:
  replicas: 1
  cdCycles: 10
  crudCycles: 10
ioSoakTest:
  replicas: 1
  duration: 6m
  # loadFactor is number of volumes for each mayastor instance
  # volumes for disruptor pods are allocated from within this "pool"
  loadFactor: 10
  protocols:
  - nvmf
  disrupt:
    # Number of disruptor pods
    podCount: 3
    # faultAfter units are seconds
    faultAfter: 51
  # fioStartDelay units are seconds
  fioStartDelay: 90
  # thinkTime units are microseconds
  fioDutyCycles:
  - thinkTime: 500000
    thinkTimeBlocks: 1000
  - thinkTime: 750000
    thinkTimeBlocks: 1000
  - thinkTime: 1250000
    thinkTimeBlocks: 2000
  - thinkTime: 1500000
    thinkTimeBlocks: 3000
  - thinkTime: 1750000
    thinkTimeBlocks: 3000
  - thinkTime: 2000000
    thinkTimeBlocks: 4000
csi:
  replicas: 1
  smallClaimSize: 50Mi
  largeClaimSize: 500Mi
uninstall:
  cleanup: 0
basicVolumeIO:
  replicas: 1
  # timeout units are seconds
  fioTimeout: 60
  # volSizeMb units are MiB
  volSizeMb: 500
  # fsVolSizeMb units are MiB
  fsVolSizeMb: 450
multiVolumesPodIO:
  volumeCount: 6
  replicas: 2
