# configuration/parameters for CI/CD e2e test runs on Hetzner-Volterra
configName: CI-volterra-hetzner
# TODO: fix platform
platform: Hetzner-Volterra
cannotRestorePools: true
hostNetworkingRequired: true
mayastorNamespace: ves-system
filteredMayastorPodCheck: 1
disableE2EAgent: true
pvcStress:
  replicas: 1
  cdCycles: 100
  crudCycles: 10
ioSoakTest:
  replicas: 1
  duration: 60m
  # loadFactor is number of volumes for each mayastor instance
  # volumes for disruptor pods are allocated from within this "pool"
  loadFactor: 10
  protocols:
  - nvmf
  # fioStartDelay units are seconds
  fioStartDelay: 90
  disrupt:
    # Number of disruptor pods
    podCount: 3
    # faultAfter units are seconds
    faultAfter: 51
  # thinkTime units are microseconds
  fioDutyCycles:
  - thinkTime: 500000
    thinkTimeBlocks: 1000
  - thinkTime: 750000
    thinkTimeBlocks: 1000
  - thinkTime: 1250000
    thinkTimeBlocks: 2000
  - thinkTime: 1500000
    thinkTimeBlocks: 3000
  - thinkTime: 1750000
    thinkTimeBlocks: 3000
  - thinkTime: 2000000
    thinkTimeBlocks: 4000
csi:
  replicas: 1
  smallClaimSize: 50Mi
  largeClaimSize: 500Mi
uninstall:
  cleanup: 0
basicVolumeIO:
  replicas: 1
  # timeout units are seconds
  fioTimeout: 120
  # volSizeMb units are MiB
  volSizeMb: 500
  # fsVolSizeMb units are MiB
  fsVolSizeMb: 450
multiVolumesPodIO:
  volumeCount: 6
  replicas: 2
