---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-monitor
  namespace: mayastor-e2e
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: log-monitor
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: log-monitor
roleRef:
  kind: ClusterRole
  name: log-monitor
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: log-monitor
    namespace: mayastor-e2e
---
