// Code generated by go-swagger; DO NOT EDIT.

package workload_monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/strfmt"
)

// PutWorkloadByRegistrantURL generates an URL for the put workload by registrant operation
type PutWorkloadByRegistrantURL struct {
	Rid strfmt.UUID
	Wid strfmt.UUID

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutWorkloadByRegistrantURL) WithBasePath(bp string) *PutWorkloadByRegistrantURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutWorkloadByRegistrantURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *PutWorkloadByRegistrantURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/wm/registrants/{rid}/workloads/{wid}"

	rid := o.Rid.String()
	if rid != "" {
		_path = strings.Replace(_path, "{rid}", rid, -1)
	} else {
		return nil, errors.New("rid is required on PutWorkloadByRegistrantURL")
	}

	wid := o.Wid.String()
	if wid != "" {
		_path = strings.Replace(_path, "{wid}", wid, -1)
	} else {
		return nil, errors.New("wid is required on PutWorkloadByRegistrantURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *PutWorkloadByRegistrantURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *PutWorkloadByRegistrantURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *PutWorkloadByRegistrantURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on PutWorkloadByRegistrantURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on PutWorkloadByRegistrantURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *PutWorkloadByRegistrantURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
