// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"mayastor-e2e/tools/extended-test-framework/workload_monitor/swagger/restapi/operations/workload_monitor"
)

// NewEtfwAPI creates a new Etfw instance
func NewEtfwAPI(spec *loads.Document) *EtfwAPI {
	return &EtfwAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		WorkloadMonitorDeleteWorkloadByRegistrantHandler: workload_monitor.DeleteWorkloadByRegistrantHandlerFunc(func(params workload_monitor.DeleteWorkloadByRegistrantParams) middleware.Responder {
			return middleware.NotImplemented("operation workload_monitor.DeleteWorkloadByRegistrant has not yet been implemented")
		}),
		WorkloadMonitorDeleteWorkloadsByRegistrantHandler: workload_monitor.DeleteWorkloadsByRegistrantHandlerFunc(func(params workload_monitor.DeleteWorkloadsByRegistrantParams) middleware.Responder {
			return middleware.NotImplemented("operation workload_monitor.DeleteWorkloadsByRegistrant has not yet been implemented")
		}),
		WorkloadMonitorGetWorkloadByRegistrantHandler: workload_monitor.GetWorkloadByRegistrantHandlerFunc(func(params workload_monitor.GetWorkloadByRegistrantParams) middleware.Responder {
			return middleware.NotImplemented("operation workload_monitor.GetWorkloadByRegistrant has not yet been implemented")
		}),
		WorkloadMonitorGetWorkloadsHandler: workload_monitor.GetWorkloadsHandlerFunc(func(params workload_monitor.GetWorkloadsParams) middleware.Responder {
			return middleware.NotImplemented("operation workload_monitor.GetWorkloads has not yet been implemented")
		}),
		WorkloadMonitorGetWorkloadsByRegistrantHandler: workload_monitor.GetWorkloadsByRegistrantHandlerFunc(func(params workload_monitor.GetWorkloadsByRegistrantParams) middleware.Responder {
			return middleware.NotImplemented("operation workload_monitor.GetWorkloadsByRegistrant has not yet been implemented")
		}),
		WorkloadMonitorPutWorkloadByRegistrantHandler: workload_monitor.PutWorkloadByRegistrantHandlerFunc(func(params workload_monitor.PutWorkloadByRegistrantParams) middleware.Responder {
			return middleware.NotImplemented("operation workload_monitor.PutWorkloadByRegistrant has not yet been implemented")
		}),
	}
}

/*EtfwAPI MayaData System Test Framework API */
type EtfwAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// WorkloadMonitorDeleteWorkloadByRegistrantHandler sets the operation handler for the delete workload by registrant operation
	WorkloadMonitorDeleteWorkloadByRegistrantHandler workload_monitor.DeleteWorkloadByRegistrantHandler
	// WorkloadMonitorDeleteWorkloadsByRegistrantHandler sets the operation handler for the delete workloads by registrant operation
	WorkloadMonitorDeleteWorkloadsByRegistrantHandler workload_monitor.DeleteWorkloadsByRegistrantHandler
	// WorkloadMonitorGetWorkloadByRegistrantHandler sets the operation handler for the get workload by registrant operation
	WorkloadMonitorGetWorkloadByRegistrantHandler workload_monitor.GetWorkloadByRegistrantHandler
	// WorkloadMonitorGetWorkloadsHandler sets the operation handler for the get workloads operation
	WorkloadMonitorGetWorkloadsHandler workload_monitor.GetWorkloadsHandler
	// WorkloadMonitorGetWorkloadsByRegistrantHandler sets the operation handler for the get workloads by registrant operation
	WorkloadMonitorGetWorkloadsByRegistrantHandler workload_monitor.GetWorkloadsByRegistrantHandler
	// WorkloadMonitorPutWorkloadByRegistrantHandler sets the operation handler for the put workload by registrant operation
	WorkloadMonitorPutWorkloadByRegistrantHandler workload_monitor.PutWorkloadByRegistrantHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *EtfwAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *EtfwAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *EtfwAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *EtfwAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *EtfwAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *EtfwAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *EtfwAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *EtfwAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *EtfwAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the EtfwAPI
func (o *EtfwAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.WorkloadMonitorDeleteWorkloadByRegistrantHandler == nil {
		unregistered = append(unregistered, "workload_monitor.DeleteWorkloadByRegistrantHandler")
	}
	if o.WorkloadMonitorDeleteWorkloadsByRegistrantHandler == nil {
		unregistered = append(unregistered, "workload_monitor.DeleteWorkloadsByRegistrantHandler")
	}
	if o.WorkloadMonitorGetWorkloadByRegistrantHandler == nil {
		unregistered = append(unregistered, "workload_monitor.GetWorkloadByRegistrantHandler")
	}
	if o.WorkloadMonitorGetWorkloadsHandler == nil {
		unregistered = append(unregistered, "workload_monitor.GetWorkloadsHandler")
	}
	if o.WorkloadMonitorGetWorkloadsByRegistrantHandler == nil {
		unregistered = append(unregistered, "workload_monitor.GetWorkloadsByRegistrantHandler")
	}
	if o.WorkloadMonitorPutWorkloadByRegistrantHandler == nil {
		unregistered = append(unregistered, "workload_monitor.PutWorkloadByRegistrantHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *EtfwAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *EtfwAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *EtfwAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *EtfwAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *EtfwAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *EtfwAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the etfw API
func (o *EtfwAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *EtfwAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/wm/registrants/{rid}/workloads/{wid}"] = workload_monitor.NewDeleteWorkloadByRegistrant(o.context, o.WorkloadMonitorDeleteWorkloadByRegistrantHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/wm/registrants/{rid}"] = workload_monitor.NewDeleteWorkloadsByRegistrant(o.context, o.WorkloadMonitorDeleteWorkloadsByRegistrantHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/wm/registrants/{rid}/workloads/{wid}"] = workload_monitor.NewGetWorkloadByRegistrant(o.context, o.WorkloadMonitorGetWorkloadByRegistrantHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/wm/workloads"] = workload_monitor.NewGetWorkloads(o.context, o.WorkloadMonitorGetWorkloadsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/wm/registrants/{rid}"] = workload_monitor.NewGetWorkloadsByRegistrant(o.context, o.WorkloadMonitorGetWorkloadsByRegistrantHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/wm/registrants/{rid}/workloads/{wid}"] = workload_monitor.NewPutWorkloadByRegistrant(o.context, o.WorkloadMonitorPutWorkloadByRegistrantHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *EtfwAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *EtfwAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *EtfwAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *EtfwAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *EtfwAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
