server:
  AppVersion: 1.0.0
  Mode: Development
  DefaultTestPlan: ET-435
  SlackNotification: true

logger:
  ReportCaller: false
  # text | json
  Formatter: json
  # debug | info | warn | error
  Level: info
  # file | stdout
  Output: stdout