pipeline {
    agent { label 'nixos-mayastor' }
    stages {
        stage('build tools') {
            steps {
                sh """
                    cd tools/e2e-fio
                    ./build.sh
                    cd ../e2e-agent
                    ./build.sh
                    cd ../e2e-fsx
                    ./build.sh
                """   
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin'
                }
                sh 'docker push mayadata/e2e-fio:latest'
                sh 'docker push mayadata/e2e-agent:latest'
                sh 'docker push mayadata/e2e-fsx:latest'
            }
        }
    }
}