// Code generated by go-swagger; DO NOT EDIT.

package test_director

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mayastor-e2e/tools/extended-test-framework/workload_monitor/models"
)

// PutTestPlanByIDReader is a Reader for the PutTestPlanByID structure.
type PutTestPlanByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutTestPlanByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutTestPlanByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutTestPlanByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutTestPlanByIDOK creates a PutTestPlanByIDOK with default headers values
func NewPutTestPlanByIDOK() *PutTestPlanByIDOK {
	return &PutTestPlanByIDOK{}
}

/* PutTestPlanByIDOK describes a response with status code 200, with default header values.

Test Plan was registered or updated
*/
type PutTestPlanByIDOK struct {
	Payload *models.TestPlan
}

func (o *PutTestPlanByIDOK) Error() string {
	return fmt.Sprintf("[PUT /td/testplans/{id}][%d] putTestPlanByIdOK  %+v", 200, o.Payload)
}
func (o *PutTestPlanByIDOK) GetPayload() *models.TestPlan {
	return o.Payload
}

func (o *PutTestPlanByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TestPlan)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutTestPlanByIDBadRequest creates a PutTestPlanByIDBadRequest with default headers values
func NewPutTestPlanByIDBadRequest() *PutTestPlanByIDBadRequest {
	return &PutTestPlanByIDBadRequest{}
}

/* PutTestPlanByIDBadRequest describes a response with status code 400, with default header values.

Bad request (malformed/invalid body content)
*/
type PutTestPlanByIDBadRequest struct {
	Payload *models.RequestOutcome
}

func (o *PutTestPlanByIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /td/testplans/{id}][%d] putTestPlanByIdBadRequest  %+v", 400, o.Payload)
}
func (o *PutTestPlanByIDBadRequest) GetPayload() *models.RequestOutcome {
	return o.Payload
}

func (o *PutTestPlanByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RequestOutcome)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
