pipeline {
    agent { label 'nixos' }
    stages {
        stage('build the actors') {
            steps {
                sh "nix-shell --run 'cd src/tools/extended-test-framework/scripts/ && ./build.sh' "
            }
        }
    }
}

