configName: "replica_perturbation"
registry: ci-registry.mayastor-ci.mayadata.io
imageTag: "nightly-stable"
poolDevice: "/dev/sdb"
test: "MQ-1807"
testPlan: "ET-388"
install: true
e2eFioImage: mayadata/e2e-fio
replicaCount: 2
steadyStateTest:
  replicas: 2
  duration: 60m

