// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"mayastor-e2e/tools/extended-test-framework/test_director/restapi/operations/test_director"
)

// NewEtfwAPI creates a new Etfw instance
func NewEtfwAPI(spec *loads.Document) *EtfwAPI {
	return &EtfwAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		TestDirectorAddEventHandler: test_director.AddEventHandlerFunc(func(params test_director.AddEventParams) middleware.Responder {
			return middleware.NotImplemented("operation test_director.AddEvent has not yet been implemented")
		}),
		TestDirectorDeleteTestPlanByIDHandler: test_director.DeleteTestPlanByIDHandlerFunc(func(params test_director.DeleteTestPlanByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation test_director.DeleteTestPlanByID has not yet been implemented")
		}),
		TestDirectorDeleteTestPlansHandler: test_director.DeleteTestPlansHandlerFunc(func(params test_director.DeleteTestPlansParams) middleware.Responder {
			return middleware.NotImplemented("operation test_director.DeleteTestPlans has not yet been implemented")
		}),
		TestDirectorDeleteTestRunByIDHandler: test_director.DeleteTestRunByIDHandlerFunc(func(params test_director.DeleteTestRunByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation test_director.DeleteTestRunByID has not yet been implemented")
		}),
		TestDirectorGetEventsHandler: test_director.GetEventsHandlerFunc(func(params test_director.GetEventsParams) middleware.Responder {
			return middleware.NotImplemented("operation test_director.GetEvents has not yet been implemented")
		}),
		TestDirectorGetTestPlanByIDHandler: test_director.GetTestPlanByIDHandlerFunc(func(params test_director.GetTestPlanByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation test_director.GetTestPlanByID has not yet been implemented")
		}),
		TestDirectorGetTestPlansHandler: test_director.GetTestPlansHandlerFunc(func(params test_director.GetTestPlansParams) middleware.Responder {
			return middleware.NotImplemented("operation test_director.GetTestPlans has not yet been implemented")
		}),
		TestDirectorGetTestRunByIDHandler: test_director.GetTestRunByIDHandlerFunc(func(params test_director.GetTestRunByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation test_director.GetTestRunByID has not yet been implemented")
		}),
		TestDirectorGetTestRunsHandler: test_director.GetTestRunsHandlerFunc(func(params test_director.GetTestRunsParams) middleware.Responder {
			return middleware.NotImplemented("operation test_director.GetTestRuns has not yet been implemented")
		}),
		TestDirectorPutTestPlanByIDHandler: test_director.PutTestPlanByIDHandlerFunc(func(params test_director.PutTestPlanByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation test_director.PutTestPlanByID has not yet been implemented")
		}),
		TestDirectorPutTestRunByIDHandler: test_director.PutTestRunByIDHandlerFunc(func(params test_director.PutTestRunByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation test_director.PutTestRunByID has not yet been implemented")
		}),
	}
}

/*EtfwAPI MayaData System Test Framework API */
type EtfwAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// TestDirectorAddEventHandler sets the operation handler for the add event operation
	TestDirectorAddEventHandler test_director.AddEventHandler
	// TestDirectorDeleteTestPlanByIDHandler sets the operation handler for the delete test plan by Id operation
	TestDirectorDeleteTestPlanByIDHandler test_director.DeleteTestPlanByIDHandler
	// TestDirectorDeleteTestPlansHandler sets the operation handler for the delete test plans operation
	TestDirectorDeleteTestPlansHandler test_director.DeleteTestPlansHandler
	// TestDirectorDeleteTestRunByIDHandler sets the operation handler for the delete test run by Id operation
	TestDirectorDeleteTestRunByIDHandler test_director.DeleteTestRunByIDHandler
	// TestDirectorGetEventsHandler sets the operation handler for the get events operation
	TestDirectorGetEventsHandler test_director.GetEventsHandler
	// TestDirectorGetTestPlanByIDHandler sets the operation handler for the get test plan by Id operation
	TestDirectorGetTestPlanByIDHandler test_director.GetTestPlanByIDHandler
	// TestDirectorGetTestPlansHandler sets the operation handler for the get test plans operation
	TestDirectorGetTestPlansHandler test_director.GetTestPlansHandler
	// TestDirectorGetTestRunByIDHandler sets the operation handler for the get test run by Id operation
	TestDirectorGetTestRunByIDHandler test_director.GetTestRunByIDHandler
	// TestDirectorGetTestRunsHandler sets the operation handler for the get test runs operation
	TestDirectorGetTestRunsHandler test_director.GetTestRunsHandler
	// TestDirectorPutTestPlanByIDHandler sets the operation handler for the put test plan by Id operation
	TestDirectorPutTestPlanByIDHandler test_director.PutTestPlanByIDHandler
	// TestDirectorPutTestRunByIDHandler sets the operation handler for the put test run by Id operation
	TestDirectorPutTestRunByIDHandler test_director.PutTestRunByIDHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *EtfwAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *EtfwAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *EtfwAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *EtfwAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *EtfwAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *EtfwAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *EtfwAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *EtfwAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *EtfwAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the EtfwAPI
func (o *EtfwAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.TestDirectorAddEventHandler == nil {
		unregistered = append(unregistered, "test_director.AddEventHandler")
	}
	if o.TestDirectorDeleteTestPlanByIDHandler == nil {
		unregistered = append(unregistered, "test_director.DeleteTestPlanByIDHandler")
	}
	if o.TestDirectorDeleteTestPlansHandler == nil {
		unregistered = append(unregistered, "test_director.DeleteTestPlansHandler")
	}
	if o.TestDirectorDeleteTestRunByIDHandler == nil {
		unregistered = append(unregistered, "test_director.DeleteTestRunByIDHandler")
	}
	if o.TestDirectorGetEventsHandler == nil {
		unregistered = append(unregistered, "test_director.GetEventsHandler")
	}
	if o.TestDirectorGetTestPlanByIDHandler == nil {
		unregistered = append(unregistered, "test_director.GetTestPlanByIDHandler")
	}
	if o.TestDirectorGetTestPlansHandler == nil {
		unregistered = append(unregistered, "test_director.GetTestPlansHandler")
	}
	if o.TestDirectorGetTestRunByIDHandler == nil {
		unregistered = append(unregistered, "test_director.GetTestRunByIDHandler")
	}
	if o.TestDirectorGetTestRunsHandler == nil {
		unregistered = append(unregistered, "test_director.GetTestRunsHandler")
	}
	if o.TestDirectorPutTestPlanByIDHandler == nil {
		unregistered = append(unregistered, "test_director.PutTestPlanByIDHandler")
	}
	if o.TestDirectorPutTestRunByIDHandler == nil {
		unregistered = append(unregistered, "test_director.PutTestRunByIDHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *EtfwAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *EtfwAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *EtfwAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *EtfwAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *EtfwAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *EtfwAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the etfw API
func (o *EtfwAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *EtfwAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/td/events"] = test_director.NewAddEvent(o.context, o.TestDirectorAddEventHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/td/testplans/{id}"] = test_director.NewDeleteTestPlanByID(o.context, o.TestDirectorDeleteTestPlanByIDHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/td/testplans"] = test_director.NewDeleteTestPlans(o.context, o.TestDirectorDeleteTestPlansHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/td/testruns/{id}"] = test_director.NewDeleteTestRunByID(o.context, o.TestDirectorDeleteTestRunByIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/td/events"] = test_director.NewGetEvents(o.context, o.TestDirectorGetEventsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/td/testplans/{id}"] = test_director.NewGetTestPlanByID(o.context, o.TestDirectorGetTestPlanByIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/td/testplans"] = test_director.NewGetTestPlans(o.context, o.TestDirectorGetTestPlansHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/td/testruns/{id}"] = test_director.NewGetTestRunByID(o.context, o.TestDirectorGetTestRunByIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/td/testRuns"] = test_director.NewGetTestRuns(o.context, o.TestDirectorGetTestRunsHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/td/testplans/{id}"] = test_director.NewPutTestPlanByID(o.context, o.TestDirectorPutTestPlanByIDHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/td/testruns/{id}"] = test_director.NewPutTestRunByID(o.context, o.TestDirectorPutTestRunByIDHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *EtfwAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *EtfwAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *EtfwAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *EtfwAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *EtfwAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
